#!/usr/bin/env bash

# Logger
lpm_logger () {
    logger -t power-profiles-monitor -s "$1"
}

# Governor
set_power_target () {
    case $1 in
        performance|balanced|power-saver)
            if [[ $EUID -ne 0 ]]; then
                systemctl --user start "power-profile-$1.target"
            else
                systemctl start "power-profile-$1.target"
            fi
            ;;
        *)
            lpm_logger "Error in [power target] configuration!"
            ;;
    esac
}

#######################################################

# Monitor
dbus-monitor --system "type='signal',path='/net/hadess/PowerProfiles',member='PropertiesChanged'" | while read -r LINE; do
    POWER_PROFILE_SW=$(echo "${LINE}" | grep 'variant' | sed -e 's/variant//g' -e 's/string//g' -e 's/\ //g' -e 's/"//g')
    if [[ -n "${POWER_PROFILE_SW}" ]]; then
        case ${POWER_PROFILE_SW} in
            performance)
                set_power_target performance
                ;;
            balanced)
                set_power_target balanced
                ;;
            power-saver)
                set_power_target power-saver
                ;;
            *)
                lpm_logger "Error getting power profile: [${POWER_PROFILE_SW}]!"
                ;;
        esac
    fi
done
